# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

# 抑制任何警告
inhibit_all_warnings!
use_frameworks!

target 'LZYStudy' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  pod 'Masonry', :git => "https://qtgit.qingtui.im/cloud/Masonry.git", :inhibit_warnings => true
  pod 'SVProgressHUD', :git => "https://qtgit.qingtui.im/cloud/SVProgressHUD.git", :inhibit_warnings => true
  # Pods for LZYStudy

  target 'LZYStudyTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'LZYStudyUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
