# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

# 抑制任何警告
inhibit_all_warnings!
use_frameworks!

target 'LZYStudy' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  pod 'AFNetworking', '~> 3.2.1',:inhibit_warnings => true
  pod 'SDWebImage', :git =>'https://github.com/SDWebImage/SDWebImage.git', :inhibit_warnings => true
  pod 'SDCycleScrollView', :git =>'https://github.com/gsdios/SDCycleScrollView.git', :inhibit_warnings => true
  pod 'Masonry', :git => 'https://github.com/SnapKit/Masonry.git', :inhibit_warnings => true
  pod 'FMDB',:git =>'https://github.com/ccgus/fmdb.git', :inhibit_warnings => true
  pod 'MJExtension', :git => 'https://github.com/CoderMJLee/MJExtension.git' ,:inhibit_warnings => true
  pod 'PPNetworkHelper', :git => 'https://github.com/jkpang/PPNetworkHelper.git', :inhibit_warnings => true
  pod 'TZImagePickerController',:git =>'https://github.com/banchichen/TZImagePickerController.git',:inhibit_warnings => true
  # pod 'MBProgressHUD',:inhibit_warnings => true
  # pod 'SVProgressHUD', :inhibit_warnings => true
  
  # Pods for LZYStudy

  target 'LZYStudyTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'LZYStudyUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
